apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: chatbot-prod



secretGenerator:
- envs:
  - .env
  name: backend-secret

replicas:
- count: 3
  name: backend
- count: 2
  name: frontend

images:
- name: quay.io/cfchase/chatbot-backend
  newTag: prod
- name: quay.io/cfchase/chatbot-frontend
  newTag: prod
labels:
- includeSelectors: true
  pairs:
    environment: production
patches:
- path: deployment-patch.yaml
