apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: chatbot-prod

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 2

images:
  - name: quay.io/cfchase/chatbot-backend
    newTag: prod
  - name: quay.io/cfchase/chatbot-frontend
    newTag: prod