apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: chatbot
  app.kubernetes.io/version: "1.0.0"

images:
  - name: quay.io/cfchase/chatbot-backend
    newTag: latest
  - name: quay.io/cfchase/chatbot-frontend
    newTag: latest