apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: chatbot-dev



secretGenerator:
- envs:
  - .env
  name: backend-secret

configMapGenerator:
- files:
  - mcp-config.json
  name: mcp-config

images:
- name: quay.io/cfchase/chatbot-backend
  newTag: latest
- name: quay.io/cfchase/chatbot-frontend
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    environment: development
patches:
- path: deployment-patch.yaml
